import { withSeo } from '@/lib/seo-metadata'
import type { Metadata } from 'next'
import Link from 'next/link'
import { bountyArticles, bountyBase, bountyDate } from '@/lib/bounty-data'
import { bountyVideo } from '@/lib/bounty-video'
import BountyCTA from '@/components/article/BountyCTA'
const url=bountyBase+'/amazon-offers/prime-day-trial-video'
const title='Prime Trial Before Prime Day: Timing Checklist Video'
const description='Watch an original 87-second guide to Prime trial timing, eligibility, price comparisons, useful benefits, and renewal reminders, with captions and transcript.'
const poster=bountyBase+'/media/bounties/prime-day-trial-poster.png'
export const metadata:Metadata=withSeo({title,description,alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{title,description,url,type:'video.other',images:[{url:poster,width:1280,height:720}],videos:[{url:bountyBase+'/media/bounties/prime-day-trial.mp4',type:'video/mp4',width:1280,height:720}]},twitter:{card:'summary_large_image',title,description,images:[poster]}})
export default function VideoPage(){
const schema={'@context':'https://schema.org','@type':'VideoObject',name:title,description,thumbnailUrl:[poster],uploadDate:bountyDate+'T01:30:00Z',duration:'PT1M27S',contentUrl:bountyBase+'/media/bounties/prime-day-trial.mp4',url,mainEntityOfPage:url,inLanguage:'en-US',isFamilyFriendly:true,publisher:{'@type':'Organization',name:'BestPickZone',url:bountyBase},transcript:bountyVideo.scenes.map(s=>s.text).join(' ')}
return <main className="mx-auto max-w-5xl px-4 py-8"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><nav aria-label="Breadcrumb" className="mb-5 text-sm text-teal-800"><Link href="/">Home</Link> / <Link href="/amazon-offers">Amazon membership guides</Link> / Video</nav><h1 className="text-3xl font-extrabold md:text-5xl">Prime trial before Prime Day: the timing checklist</h1><p className="mt-4 text-sm text-slate-600">Original BestPickZone video • 1 minute 27 seconds • October 3, 2026 • Synthetic narration</p><p className="my-4 text-sm leading-6 text-slate-700">As an Amazon Associate, BestPickZone earns from qualifying purchases. We may earn bounties from eligible sign-ups through our affiliate links, at no extra cost to you.</p><video controls playsInline preload="metadata" poster="/media/bounties/prime-day-trial-poster.png" width="1280" height="720" className="my-6 h-auto w-full rounded-2xl bg-slate-950" aria-label="Prime trial timing video"><source src="/media/bounties/prime-day-trial.mp4" type="video/mp4"/><track kind="captions" src="/media/bounties/prime-day-trial.vtt" srcLang="en" label="English" default/>Your browser does not support inline video. <a href="/media/bounties/prime-day-trial.mp4">Download the MP4</a>.</video><p className="text-lg leading-8">Use this short checklist to prepare before a confirmed shopping event. Check your own account&apos;s trial offer and renewal terms; discounts and eligibility are never guaranteed. For examples, membership alternatives, and official sources, read the <Link href="/amazon-offers/prime-free-trial-before-prime-day" className="font-semibold text-teal-800 underline">complete Prime Day trial guide</Link>.</p><div className="my-7"><BountyCTA article={bountyArticles[0]} placement="video"/></div><section className="rounded-3xl border border-slate-200 p-6 md:p-9"><h2 className="text-2xl font-bold">Full transcript</h2>{bountyVideo.scenes.map(s=><div key={s.title} className="mt-6"><h3 className="text-lg font-bold">{Math.floor(s.start/60)}:{String(Math.floor(s.start%60)).padStart(2,'0')} — {s.title}</h3><p className="mt-2 leading-8 text-slate-700">{s.text}</p></div>)}</section><p className="my-6 text-sm text-slate-600">Original graphics, script, and production by BestPickZone. No Amazon product imagery or third-party music. <a className="underline" href="/media/bounties/prime-day-trial.mp4" download>Download the video</a> · <a className="underline" href="/media/bounties/prime-day-trial-transcript.txt">Plain-text transcript</a></p></main>
}
