import type { Metadata } from 'next'
import Link from 'next/link'
import Breadcrumb from '@/components/ui/Breadcrumb'
import BreadcrumbJsonLd from '@/components/seo/BreadcrumbJsonLd'
import { withArticleMetadataDefaults } from '@/lib/article-metadata'

const url = 'https://bestpickzone.com/mahjong/mahjong-set-vs-mahjong-card'
const published = '2026-09-19T00:00:00Z'
const description = 'A clear American Mahjong beginner guide to the difference between a Mahjong set and the annual NMJL card—what each does, what to buy first, and what to skip.'

export const metadata: Metadata = withArticleMetadataDefaults({ title: 'Mahjong Set vs. Mahjong Card: What You Need', description, alternates: { canonical: url }, openGraph: { title: 'Mahjong Set vs. Mahjong Card: What You Need', description, url, type: 'article' }, twitter: { card: 'summary_large_image', title: 'Mahjong Set vs. Mahjong Card', description } }, { category: 'mahjong', publishedTime: published, modifiedTime: published, section: 'Mahjong', url, tags: ['American Mahjong card', 'Mahjong set', 'NMJL card'] })

const articleSchema = { '@context': 'https://schema.org', '@type': 'Article', headline: 'Mahjong Set vs. Mahjong Card: What You Need', description, datePublished: published, dateModified: published, mainEntityOfPage: url, author: { '@type': 'Organization', name: 'BestPickZone Editorial Team' }, publisher: { '@type': 'Organization', name: 'BestPickZone' } }

export default function Page() { return <main className="mx-auto max-w-4xl px-4 py-10">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
  <BreadcrumbJsonLd trail={[{ name: 'Home', path: '/' }, { name: 'Mahjong', path: '/mahjong' }, { name: 'Mahjong Set vs. Mahjong Card' }]} />
  <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Mahjong', href: '/mahjong' }, { label: 'Mahjong Set vs. Mahjong Card' }]} />
  <header className="mb-10 rounded-[2rem] bg-[linear-gradient(135deg,#12343b,#246a62,#d28b24)] p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-100">American Mahjong explained</p><h1 className="mt-3 max-w-4xl text-4xl font-black leading-tight md:text-5xl">Mahjong set vs. Mahjong card: what new players actually need</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-teal-50">A Mahjong set gives you the physical tools to play: tiles, racks, pushers, dice, and storage. The annual card tells American Mahjong players which hands are valid for that year. If you are joining an established game, ask whether the host supplies tiles and which current card the group uses before buying anything. Most beginners need a lesson and a card before they need an expensive set.</p></header>
  <section className="mb-10 overflow-hidden rounded-[2rem] border border-teal-100 bg-white shadow-sm"><div className="grid md:grid-cols-2"><div className="p-7"><p className="text-sm font-bold uppercase tracking-wide text-teal-700">A Mahjong set</p><h2 className="mt-2 text-3xl font-black text-slate-900">The physical game equipment</h2><p className="mt-4 leading-8 text-slate-700">Tiles, four player racks, pushers, dice, and a case or bag. A set lets a group build walls, sort tiles, and play at a table. It does not teach you which hand to aim for or make an out-of-date annual card usable.</p></div><div className="border-t border-teal-100 bg-teal-50 p-7 md:border-l md:border-t-0"><p className="text-sm font-bold uppercase tracking-wide text-teal-700">The annual card</p><h2 className="mt-2 text-3xl font-black text-slate-900">The American Mahjong hand reference</h2><p className="mt-4 leading-8 text-slate-700">For NMJL-style American Mahjong, the current card lists the legal hand patterns for the year. It is not a deck of cards and it is not included automatically with every tile set. It is the live reference players use to choose and complete a hand.</p></div></div></section>
  <section className="space-y-8"><section><h2 className="text-3xl font-black text-slate-900">What a Mahjong set does</h2><div className="mt-4 space-y-5 leading-8 text-slate-700"><p>A Mahjong set is the equipment box. In an American Mahjong game, it normally includes tiles plus four racks and pushers so each player can organize a hand and move a wall. Many commercial bundles add dice, chips, a wind indicator, an instruction sheet, or a carrying bag. Those extras can make a host’s life easier, but the set remains a physical object. It does not determine the legal hands, settle a rules disagreement, or tell a new player which discards are smart.</p><p>This distinction matters because online listings often make a complete-looking set feel like the entire game. It is enough for a casual learning session only if the group has already agreed on rules and has a source for valid hands. A beautiful tile case can be a worthwhile gift for a regular host. For a player joining a weekly group that already owns several sets, it may be unnecessary. Ask the host before buying one—many game nights need one shared set, not four individual sets.</p><p>There is also no single universal Mahjong set. American Mahjong, Chinese Mahjong, and Japanese Riichi Mahjong use different conventions and may need different tile configurations or accessories. Do not choose based only on color, a low price, or a title that says “Mahjong.” First identify the version your group plays. Then choose a compatible, readable set with the racks, pushers, and storage that match how the group meets.</p></div></section>
  <section className="rounded-[2rem] bg-slate-900 p-7 text-white"><h2 className="text-3xl font-black">What the annual card does in American Mahjong</h2><div className="mt-4 space-y-5 leading-8 text-slate-200"><p>American Mahjong is distinctive because the National Mah Jongg League publishes an annual card of valid hands. The current 2026 card has nine sections and 72 hands, according to the American Mahjongg Association’s card guide. Players use the card from the beginning of a game to identify possible hand patterns, then adapt as they draw, pass, and discard tiles. A hand only wins if it matches a line on the current card under the rules the group follows.</p><p>The annual reset is why a card is not a one-time purchase in the way a set can be. A card from a prior year may still be useful for practice, vocabulary, or learning pattern recognition, but it is not the current reference for a group that plays the 2026 card. The National Mah Jongg League currently offers 2026 standard and large-print cards through its own store. <a href="https://nationalmahjonggleague.org/store.aspx" target="_blank" rel="noopener noreferrer" className="font-bold text-amber-200 underline">Check the official NMJL 2026 card</a>.</p><p>Do not confuse the annual card with a general rules book. It tells you the hand options; table procedure still includes steps such as the Charleston, drawing, discarding, exposures, and declaring Mah Jongg. A lesson, rule companion, or experienced table partner is the better first answer when you are asking “how do I play?” The card becomes much more useful once someone shows you how to read it without trying to memorize every line at once.</p></div></section>
  <section><h2 className="text-3xl font-black text-slate-900">What should you buy first?</h2><div className="mt-4 grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 className="text-xl font-bold text-slate-900">You are joining a group</h3><p className="mt-3 leading-7 text-slate-700">Ask the host what they supply. If the table has sets, buy the current card and take a lesson before purchasing tiles. You may need no set at all.</p></div><div className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 className="text-xl font-bold text-slate-900">You are starting a group</h3><p className="mt-3 leading-7 text-slate-700">Buy one compatible, complete set and make sure every player has access to the current card. Prioritize readable tiles and four usable player stations over decorative extras.</p></div><div className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 className="text-xl font-bold text-slate-900">You are buying a gift</h3><p className="mt-3 leading-7 text-slate-700">Confirm the recipient’s version first. A current card is useful for an American player; a premium set is better for an established host with a clear style preference.</p></div></div></section>
  <section className="rounded-[2rem] border border-amber-100 bg-amber-50 p-7"><h2 className="text-3xl font-black text-slate-900">Three beginner mistakes to avoid</h2><ol className="mt-5 list-decimal space-y-4 pl-6 leading-8 text-slate-700"><li><strong>Buying a set before asking what version the group plays.</strong> A set that looks right online can still be wrong for Chinese or Japanese Riichi play, or incomplete for an American table.</li><li><strong>Assuming a card is in every set.</strong> Most commercial tile bundles are equipment packages. Check whether your group requires the current NMJL card and order it from the appropriate source.</li><li><strong>Buying every accessory before playing.</strong> Start with tiles, player stations, the right card, and a lesson. Add a mat, premium pushers, chips, or a display case only after you know what the table actually needs.</li></ol></section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-7"><h2 className="text-3xl font-black text-slate-900">How the set and card work together at the table</h2><div className="mt-4 space-y-5 leading-8 text-slate-700"><p>Think of the set as the board and pieces, and the card as the season’s puzzle menu. The tiles give you the raw material. Your rack holds the developing hand. The card gives you a target pattern to pursue. During the Charleston, you pass tiles with potential card lines in mind. On every turn, you draw a tile, check whether it improves a live hand, and discard something that does not fit. That interaction is why neither purchase replaces the other for a self-hosted American Mahjong game.</p><p>It is also why players should resist premature perfectionism. You do not need a $200 case, a matching mat, custom pushers, and several card holders to learn. A clear basic set, the correct annual card, and a patient table are enough. Once you have played enough to know whether your group values portability, a polished home setup, or regular travel, then the equipment choices become meaningful rather than speculative.</p></div></section>
  <section className="rounded-[2rem] border border-teal-100 bg-teal-50 p-7"><h2 className="text-3xl font-black text-slate-900">Final verdict</h2><p className="mt-4 max-w-3xl leading-8 text-slate-700">If you are a new American Mahjong player joining an existing group, buy or borrow the current card before you buy a set. If you are starting a table, you need both: a compatible physical set and a current card for the rules your group follows. Start simple, verify your version, and let real game nights tell you whether you need premium accessories later.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/mahjong/best-mahjong-sets-for-beginners" className="rounded-full bg-yellow-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-yellow-300">Best Mahjong sets for beginners</Link><Link href="/mahjong/best-american-mahjong-sets-on-amazon" className="rounded-full bg-yellow-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-yellow-300">Best American Mahjong sets on Amazon</Link><Link href="/mahjong" className="rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-800">Explore Mahjong guides</Link></div></section>
  </section>
</main> }
