export const bountyDate = '2026-10-03'
export const bountyTag = 'fitnessbankd-20'
export const bountyBase = 'https://bestpickzone.com'
export const bountyVideoSlug = 'prime-day-trial-video'
export type BountyArticle = { slug: string; title: string; description: string; program: string; rate: number; reason: string; destination: string; cta: string; group: 'Prime' | 'Reading' | 'Business'; visualTitle: string; steps: [string,string,string]; caution: string }
export const bountyArticles: BountyArticle[] = [
{slug:'prime-free-trial-before-prime-day',title:'Why Start a Prime Free Trial Before Prime Day?',description:'Plan a Prime trial around confirmed sale dates, compare real prices, test useful benefits, and track renewal without assuming every shopper qualifies.',program:'Prime Free Trial',rate:40,reason:'Flagship shopping-event intent across all product hubs; low initial commitment for eligible customers.',destination:'https://www.amazon.com/prime',cta:'Check Prime trial eligibility on Amazon',group:'Prime',visualTitle:'Plan your Prime trial',steps:['Confirm the sale dates','Fit the sale inside your trial','Review before renewal'],caution:'A trial is not a guarantee of discounts or eligibility.'},
{slug:'prime-for-young-adults-trial',title:'Prime for Young Adults Trial: Who Should Try It?',description:'Check Prime for Young Adults eligibility, evaluate delivery through a normal term, and decide whether the discounted renewal fits your routine.',program:'Prime for Young Adults Trial',rate:40,reason:'Distinct student and young-adult audience; ties to existing dorm, study and college guides.',destination:'https://www.amazon.com/joinyoungadult',cta:'Check Young Adults eligibility on Amazon',group:'Prime',visualTitle:'Test a normal term',steps:['Verify your eligibility','Try everyday delivery','Review the renewal cost'],caution:'Membership eligibility does not guarantee a new trial.'},
{slug:'prime-access-eligibility-value',title:'Prime Access: Eligibility and When It Is Worth It',description:'Understand Prime Access verification, monthly costs, grocery limitations, and a practical way to judge whether discounted Prime suits your household.',program:'Prime Access Free Trial or Paid Membership',rate:40,reason:'Specific qualification intent and a useful lower-cost alternative to standard Prime.',destination:'https://www.amazon.com/qualify',cta:'Check Prime Access eligibility on Amazon',group:'Prime',visualTitle:'A household value check',steps:['Verify privately on Amazon','Compare a normal basket','Count costs actually avoided'],caution:'A discounted membership still has to fit your budget.'},
{slug:'is-amazon-prime-paid-membership-worth-it',title:'Is Paid Amazon Prime Worth It? Monthly vs Annual',description:'Compare monthly and annual Prime using delivery costs, entertainment you actually use, and realistic shopping habits before committing to a paid plan.',program:'Prime Paid Membership',rate:40,reason:'Captures paid-plan intent and trial-ineligible shoppers; distinct recurring-value calculation.',destination:'https://www.amazon.com/prime',cta:'Compare current Prime plans on Amazon',group:'Prime',visualTitle:'Count only real value',steps:['Delivery costs avoided','Entertainment replaced','Less extra spending'],caution:'Annual savings depend on using the membership all year.'},
{slug:'audible-premium-plus-annual-membership',title:'Audible Premium Plus Annual: Is It Worth It?',description:'Evaluate annual Audible credits, listening capacity, expiration, and books you keep before choosing a full-year Premium Plus membership.',program:'Audible Premium Plus Annual Membership',rate:25,reason:'Strong books fit and high-value purchase intent from established listeners.',destination:'https://www.amazon.com/hz/audible/mlp/membership/premiumplus/annual',cta:'Check Audible annual plans on Amazon',group:'Reading',visualTitle:'Before buying annual audio',steps:['List books you want','Estimate listening hours','Check credit deadlines'],caution:'Unused credits are not a cash balance.'},
{slug:'audible-standard-free-trial',title:'Audible Standard Trial: Access, Limits and Value',description:'Test Audible Standard with one realistic listening plan and understand how its monthly selections differ from Premium Plus books you keep.',program:'Audible Standard Free Trial',rate:20,reason:'Strong audiobook audience match; low-commitment trial with a material access-versus-ownership decision.',destination:'https://www.amazon.com/hz/audible/mlp',cta:'Check Audible Standard trial options on Amazon',group:'Reading',visualTitle:'Access or a book to keep?',steps:['Standard: monthly selection','Premium: credit purchase','Choose for your routine'],caution:'Standard selections depend on continued membership.'},
{slug:'amazon-business-account-for-small-business',title:'Amazon Business: Is a Free Account Worth It?',description:'See when an Amazon Business account helps a small office, what to prepare for verification, and how to compare pricing and optional paid plans.',program:'Amazon Business',rate:15,reason:'WFH and office-supply fit; free account registration removes a subscription purchase barrier.',destination:'https://business.amazon.com',cta:'Explore Amazon Business registration',group:'Business',visualTitle:'Make work buying clearer',steps:['Separate work purchases','Compare a repeat basket','Assign buying responsibility'],caution:'Free account registration is separate from paid plans.'},
{slug:'audible-12-month-gift-membership',title:'Audible 12-Month Gift: Who Is It Right For?',description:'Choose an Audible gift for the right listener and understand existing-member credits, redemption, expiration, and nonrenewing gift terms.',program:'Audible Gift Membership: 12-month plan',rate:10,reason:'Gift-buying intent complements book recommendation pages and allows recipient choice.',destination:'https://www.amazon.com/hz/audible/gift-membership-detail',cta:'View 12-month Audible gift options on Amazon',group:'Reading',visualTitle:'Give the right audio gift',steps:['Confirm a listening habit','Check existing membership','Review gift redemption'],caution:'A gift does not replace an existing subscription bill.'},
{slug:'kindle-unlimited-free-trial-reading-test',title:'Kindle Unlimited Trial: Test the Catalog First',description:'Check the books you want, measure your reading pace, and compare borrowing with ownership before a Kindle Unlimited trial renews.',program:'Kindle Unlimited Free Trial',rate:3,reason:'Excellent fit with the strongest books silo; lower bounty offset by clear low-commitment reading intent.',destination:'https://www.amazon.com/kindleunlimited',cta:'Check Kindle Unlimited trial options on Amazon',group:'Reading',visualTitle:'Build a reading test',steps:['Check ten wanted titles','Read a realistic small queue','Review access and renewal'],caution:'Not every Kindle ebook is included.'},
{slug:'kindle-unlimited-24-month-gift',title:'Kindle Unlimited 24-Month Gift: Worth Two Years?',description:'Decide whether a two-year Kindle Unlimited gift fits the recipient, compare duration costs, and check catalog and redemption limits.',program:'Kindle Unlimited Membership: 24-month plan',rate:10,reason:'Higher-value reading gift with a distinct long-duration purchase decision, not another trial variant.',destination:'https://www.amazon.com/gp/kindle/ku/gift_landing',cta:'View 24-month Kindle Unlimited gifts on Amazon',group:'Reading',visualTitle:'A gift for a proven habit',steps:['Confirm catalog fit','Compare gift durations','Check the recipient account'],caution:'Two years of access does not mean permanent ownership.'},
]
export function bountyHref(a: BountyArticle) { const u = new URL(a.destination); u.searchParams.set('tag',bountyTag); return u.toString() }
export function bountyPath(a: BountyArticle) { return `/amazon-offers/${a.slug}` }
