export type BuyingGuide = { slug: string; silo: 'mahjong' | 'coffee' | 'wfh'; title: string; description: string; visual: [string, string, string] }
export const buyingGuides: BuyingGuide[] = [
  { slug: 'best-folding-tables-for-mahjong', silo: 'mahjong', title: 'Best Folding Tables for Mahjong: Playing Space, Legroom, and Storage Compared', description: 'Compare folding Mahjong tables by playing area, rack layout, legroom checks, weight, and folded storage—not just the size printed on the box.', visual: ['Measure the rack layout', 'Check knees and braces', 'Measure the storage opening'] },
  {"slug": "best-monitor-arms-for-shallow-desks", "silo": "wfh", "title": "Best Monitor Arms for Shallow Desks Against a Wall", "description": "Compare monitor arms by wall clearance, folded geometry, VESA fit, load limits, and the viewing distance left on a shallow desk.", "visual": ["Measure the screen position", "Plan the folded arm path", "Check clamp and cable space"]},
  {"slug": "best-espresso-grinders-for-breville-bambino", "silo": "coffee", "title": "Best Espresso Grinders for the Breville Bambino and Bambino Plus", "description": "Choose a Bambino grinder by espresso adjustment, 54mm dosing workflow, basket type, and timed versus weighed doses.", "visual": ["Identify your basket", "Choose cup or cradle", "Weigh and adjust one variable"]},
  {"slug": "best-carrying-bags-for-american-mahjong-sets", "silo": "mahjong", "title": "Best Carrying Bags for Full-Size American Mahjong Sets", "description": "Compare Mahjong bags by published pouch fit, tiles, racks, pushers, cards, and mat limitations\u2014with interior-dimension gaps clearly identified.", "visual": ["Measure each packed component", "Check pouch limits and spares", "Carry the mat separately if needed"]},
  {"slug": "best-low-profile-espresso-scales", "silo": "coffee", "title": "Best Low-Profile Espresso Scales for Small Drip Trays", "description": "Compare compact espresso scales by footprint and cup clearance, with a worked height calculation and machine-specific fit checks.", "visual": ["Measure tray support", "Subtract scale and cup height", "Keep controls and discharge clear"]},
  {"slug": "best-usb-c-docks-for-two-monitors", "silo": "wfh", "title": "Best USB-C Docks for Two External Monitors: Check Your Laptop Before Buying", "description": "Choose a dual-monitor dock by laptop, operating system, native display limits, DisplayLink requirements, resolution, and charging power.", "visual": ["Identify the exact laptop", "Match the display path", "Verify both screens and charging"]},
  {"slug": "best-mahjong-mats-for-small-tables", "silo": "mahjong", "title": "Best Mahjong Mats for Small Tables and Easy Storage", "description": "Choose a Mahjong mat or fitted cover by table shape, rack placement, backing, cleaning, and roll-versus-fold storage.", "visual": ["Check all four corners", "Place racks across no edge", "Match storage to the material"]},
  {"slug": "best-burr-grinders-french-press-cold-brew", "silo": "coffee", "title": "Best Electric Burr Grinders for French Press and Cold Brew", "description": "Compare brew grinders by coarse adjustment, batch dose, hopper and bin limits, cleaning, and the extra loads a cold-brew concentrate needs.", "visual": ["Calculate the dry dose", "Compare load and bin capacity", "Adjust grind with the recipe fixed"]},
  {"slug": "best-coffee-makers-for-low-cabinets", "silo": "coffee", "title": "Best Coffee Makers for Low Kitchen Cabinets", "description": "Compare front-fill and compact coffee makers by closed height, reservoir access, filter loading, serving capacity, and operating clearance.", "visual": ["Measure the lowest cabinet lip", "Rehearse filling and filter access", "Check operating placement"]},
  {"slug": "best-video-call-lighting-for-glasses", "silo": "wfh", "title": "Best Video-Call Lighting for People Who Wear Glasses", "description": "Choose video-call lighting by placement, reflected glare, panel size, power requirements, and the space around your monitor.", "visual": ["Isolate each reflection source", "Move the light off camera axis", "Test natural head movement"]},
]
export const guideDate = '2026-09-27'
