export type BuyingGuide = { slug: string; silo: 'mahjong' | 'coffee' | 'wfh' | 'books' | 'home-kitchen'; title: string; description: string; visual: [string, string, string]; date?: string; publishedDate?: string }
export const buyingGuides: BuyingGuide[] = [
  {"slug": "kitchenaid-pasta-roller-vs-pasta-press", "silo": "home-kitchen", "title": "KitchenAid Pasta Roller vs. Pasta Press: Which Attachment Should You Buy?", "description": "Choose a KitchenAid roller for sheets and ribbons or the KSMPEXTA press for tubes and shapes. Compare dough, mixer fit, current variants, cleaning, and storage.", "visual": ["Choose the pasta shape first", "Match the attachment and dough recipe", "Budget for preparation and cleanup"], "date": "2026-09-30"},
  {"slug": "best-pizza-peels-ooni-koda-12", "silo": "home-kitchen", "title": "Best Pizza Peels for the Ooni Koda 12: Launching vs. Turning", "description": "Choose a 12-inch launching peel and decide whether a small turning peel earns its place. Compare Ooni fit, wood and metal, handle space, and unnecessary extras.", "visual": ["Confirm Koda 12, not Koda 2", "Choose a 12-inch launching blade", "Add a turning peel only for its job"], "date": "2026-09-30"},
  {"slug": "best-mahjong-racks-pushers-oversized-tiles", "silo": "mahjong", "title": "Best Mahjong Racks and Pushers for Oversized Tiles", "description": "Choose Mahjong racks by tile width, thickness, wall length, exposure shelf, and pusher fit. Compare documented 20-inch options and avoid misleading size claims.", "visual": ["Measure width, height, and thickness", "Check the hand and the complete wall", "Confirm shelf fit before ordering"], "date": "2026-09-30"},
  {"slug": "ninja-creami-containers-compatibility", "silo": "home-kitchen", "title": "Which Ninja CREAMi Containers Fit Your Machine? Original, Deluxe, and Swirl Compared", "description": "Match Ninja CREAMi Original, Deluxe, XL, and Swirl model numbers to genuine container part families. Avoid confusing equal capacity with compatible fit.", "visual": ["Read the full machine model", "Match the container part family", "Check lids, nozzles, and included pieces"], "date": "2026-09-30"},
  {"slug": "elgato-stream-deck-mk2-vs-logitech-mx-creative-console", "silo": "wfh", "title": "Elgato Stream Deck MK.2 vs. Logitech MX Creative Console: Keys or Dials?", "description": "Compare the Stream Deck MK.2, full MX Creative Console, and standalone MX Keypad by software, buttons, dials, desk setup, and real workflow needs.", "visual": ["Count visible commands", "Decide whether you need continuous controls", "Check your exact app and operating system"], "date": "2026-09-30", "publishedDate": "2026-01-01"},

  {"slug": "best-espresso-grinders-gaggia-classic-pro", "silo": "coffee", "title": "Best Espresso Grinders for the Gaggia Classic Pro: Dialing In Without the Guesswork", "description": "Compare Encore ESP, J-Ultra, and Mignon Specialità for the Gaggia Classic Pro: adjustment, retention, dosing, budget tiers, and upgrade priorities.", "visual": ["Choose your basket and dose", "Match the grinder to your routine", "Keep the Gaggia brew routine consistent"], "date": "2026-09-30"},
  {"slug": "best-bottomless-portafilters-gaggia-classic-pro", "silo": "coffee", "title": "Best Bottomless Portafilters for the Gaggia Classic Pro: Fit, Baskets, and What to Buy", "description": "Choose a Gaggia bottomless portafilter by lug fit, Classic Pro and E24 compatibility, basket depth, and clearance. Compare KNODOS, Normcore, and IMS.", "visual": ["Confirm the exact Gaggia variant", "Check basket rim, depth, and headspace", "Use the view to diagnose your puck"], "date": "2026-09-30"},
  {"slug": "daring-greatly-vs-the-gifts-of-imperfection", "silo": "books", "title": "Daring Greatly vs. The Gifts of Imperfection: Which Brené Brown Book First?", "description": "Choose Daring Greatly for courage and vulnerability or The Gifts of Imperfection for perfectionism. Compare tone, practical use, and reading order.", "visual": ["Name your reason for reading", "Choose courage or perfectionism first", "Buy one and try a useful idea"], "date": "2026-09-30"},

  { slug: 'best-folding-tables-for-mahjong', silo: 'mahjong', title: 'Best Folding Tables for Mahjong: Playing Space, Legroom, and Storage Compared', description: 'Compare folding Mahjong tables by playing area, rack layout, legroom checks, weight, and folded storage—not just the size printed on the box.', visual: ['Measure the rack layout', 'Check knees and braces', 'Measure the storage opening'] },
  {"slug": "best-monitor-arms-for-shallow-desks", "silo": "wfh", "title": "Best Monitor Arms for Shallow Desks Against a Wall", "description": "Compare monitor arms by wall clearance, folded geometry, VESA fit, load limits, and the viewing distance left on a shallow desk.", "visual": ["Measure the screen position", "Plan the folded arm path", "Check clamp and cable space"]},
  {"slug": "best-espresso-grinders-for-breville-bambino", "silo": "coffee", "title": "Best Espresso Grinders for the Breville Bambino and Bambino Plus", "description": "Choose a Bambino grinder by espresso adjustment, 54mm dosing workflow, basket type, and timed versus weighed doses.", "visual": ["Identify your basket", "Choose cup or cradle", "Weigh and adjust one variable"]},
  {"slug": "best-carrying-bags-for-american-mahjong-sets", "silo": "mahjong", "title": "Best Carrying Bags for Full-Size American Mahjong Sets", "description": "Compare Mahjong bags by published pouch fit, tiles, racks, pushers, cards, and mat limitations\u2014with interior-dimension gaps clearly identified.", "visual": ["Measure each packed component", "Check pouch limits and spares", "Carry the mat separately if needed"]},
  {"slug": "best-low-profile-espresso-scales", "silo": "coffee", "title": "Best Low-Profile Espresso Scales for Small Drip Trays", "description": "Compare compact espresso scales by footprint and cup clearance, with a worked height calculation and machine-specific fit checks.", "visual": ["Measure tray support", "Subtract scale and cup height", "Keep controls and discharge clear"]},
  {"slug": "best-usb-c-docks-for-two-monitors", "silo": "wfh", "title": "Best USB-C Docks for Two External Monitors: Check Your Laptop Before Buying", "description": "Choose a dual-monitor dock by laptop, operating system, native display limits, DisplayLink requirements, resolution, and charging power.", "visual": ["Identify the exact laptop", "Match the display path", "Verify both screens and charging"]},
  {"slug": "best-mahjong-mats-for-small-tables", "silo": "mahjong", "title": "Best Mahjong Mats for Small Tables and Easy Storage", "description": "Choose a Mahjong mat or fitted cover by table shape, rack placement, backing, cleaning, and roll-versus-fold storage.", "visual": ["Check all four corners", "Place racks across no edge", "Match storage to the material"]},
  {"slug": "best-burr-grinders-french-press-cold-brew", "silo": "coffee", "title": "Best Electric Burr Grinders for French Press and Cold Brew", "description": "Compare brew grinders by coarse adjustment, batch dose, hopper and bin limits, cleaning, and the extra loads a cold-brew concentrate needs.", "visual": ["Calculate the dry dose", "Compare load and bin capacity", "Adjust grind with the recipe fixed"]},
  {"slug": "best-coffee-makers-for-low-cabinets", "silo": "coffee", "title": "Best Coffee Makers for Low Kitchen Cabinets", "description": "Compare front-fill and compact coffee makers by closed height, reservoir access, filter loading, serving capacity, and operating clearance.", "visual": ["Measure the lowest cabinet lip", "Rehearse filling and filter access", "Check operating placement"]},
  {"slug": "best-video-call-lighting-for-glasses", "silo": "wfh", "title": "Best Video-Call Lighting for People Who Wear Glasses", "description": "Choose video-call lighting by placement, reflected glare, panel size, power requirements, and the space around your monitor.", "visual": ["Isolate each reflection source", "Move the light off camera axis", "Test natural head movement"]},
]
export const guideDate = '2026-09-27'
