import type { Metadata } from 'next'
import Link from 'next/link'
import Breadcrumb from '@/components/ui/Breadcrumb'
import BreadcrumbJsonLd from '@/components/seo/BreadcrumbJsonLd'
import ItemListJsonLd from '@/components/seo/ItemListJsonLd'
import { withArticleMetadataDefaults } from '@/lib/article-metadata'

const guides = [
  { href: '/mahjong/best-mahjong-sets-for-beginners', title: 'Best Mahjong Sets for Beginners', text: 'A practical first-buy guide for American Mahjong players: 166 tiles, racks, pushers, cases, and the mistakes that make a new set unusable.', status: 'Live' },
  { href: '/mahjong/best-american-mahjong-sets-on-amazon', title: 'Best American Mahjong Sets on Amazon', text: 'A dedicated comparison for players who need American-style tiles, jokers, racks, pushers, and carrying cases.', status: 'Live' },
  { href: '/mahjong/best-travel-mahjong-sets', title: 'Best Travel Mahjong Sets', text: 'Compact and portable options for trips, cruises, RVs, and game nights away from home.', status: 'Live' },
  { title: 'Mahjong Set vs. Mahjong Card', text: 'What new American Mahjong players actually need to buy, what the annual card does, and why a set alone is not always enough.', status: 'Planned' },
  { title: 'Best Mahjong Accessories for Game Night', text: 'Mats, racks, pushers, card holders, score pads, table covers, and carrying cases.', status: 'Planned' },
  { title: 'How to Choose a Mahjong Set', text: 'A buyer’s guide to American, Chinese, Japanese Riichi, and Taiwanese tile systems before you choose a set.', status: 'Planned' },
  { title: 'Best Book to Learn Mahjong', text: 'A beginner-friendly guide to learning the rules, table vocabulary, and decision-making without buying the wrong instructional book.', status: 'Planned' },
] as const

export const metadata: Metadata = withArticleMetadataDefaults({ title: 'Mahjong Guides for Beginners | BestPickZone', description: 'American Mahjong set, accessory, and learning guides for new players—starting with the equipment you need for a first game night.', alternates: { canonical: 'https://bestpickzone.com/mahjong' } }, { category: 'mahjong', publishedTime: '2026-09-19T00:00:00Z', section: 'Mahjong', url: 'https://bestpickzone.com/mahjong' })

export default function MahjongHubPage() { return <main className="mx-auto max-w-5xl px-4 py-10">
  <BreadcrumbJsonLd trail={[{ name: 'Home', path: '/' }, { name: 'Mahjong' }]} />
  <ItemListJsonLd name="Mahjong Guides" items={guides.filter((guide) => 'href' in guide).map((guide) => ({ name: guide.title, path: guide.href }))} />
  <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Mahjong' }]} />
  <header className="mb-10 rounded-[2rem] bg-[linear-gradient(135deg,#12343b,#236a62,#d28b24)] p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-100">New player hub</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Mahjong guides for beginners</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-teal-50">The first question is not which set looks nicest. It is which version of Mahjong your group plays. This section begins with American Mahjong equipment, then expands into travel sets, accessories, and learning resources so new players can buy confidently.</p></header>
  <section className="mb-10 rounded-[2rem] border border-teal-100 bg-white p-7 shadow-sm"><h2 className="text-3xl font-black text-slate-900">What is Mahjong?</h2><div className="mt-5 space-y-5 leading-8 text-slate-700"><p>Mahjong is a tile game that originated in China and is most often played by four people. Players draw and discard tiles while trying to build a winning hand, but the exact hands, scoring, tile set, and table customs change by version. That variation is the first thing a new player needs to understand: “Mahjong” is a family of related games, not one universal rulebook. A Chinese-style game, Japanese Riichi game, and American Mahjong game can all use familiar-looking tiles while asking players to make decisions in very different ways.</p><p>At its core, the appeal is easy to see. A round combines pattern recognition, odds, memory, table awareness, and luck, but it is also tactile and social. You are reading tiles, passing or discarding with other people, and gradually learning the small habits that make a table move smoothly. It can feel intimidating at first because the tiles have symbols and the vocabulary is new. Once a group has one patient teacher and a consistent format, though, the basic rhythm becomes clear: sort, choose a direction, draw, discard, and keep refining the hand you are trying to make.</p></div></section>
  <section className="mb-10 grid gap-6 md:grid-cols-2"><div className="rounded-[2rem] bg-teal-50 p-7"><h2 className="text-2xl font-black text-slate-900">Why Mahjong is becoming popular again</h2><p className="mt-4 leading-7 text-slate-700">The current interest is not just about decorative sets. Mahjong creates an in-person ritual at a time when many people are actively looking for phone-free ways to meet. Lessons, clubs, pop-up games, and regular home tables give players a reason to gather that is more interactive than a casual drink but less formal than a league sport. Recent reporting has documented expanding game nights and clubs across the United States; Axios reported in 2026 that Evite data showed Mahjong game nights up 94% year over year. <a className="font-bold text-teal-800 underline" href="https://www.axios.com/local/dallas/2026/08/10/mahjong-room-home-design" target="_blank" rel="noopener noreferrer">Read the report</a>.</p></div><div className="rounded-[2rem] border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black text-slate-900">A quick history and a respectful starting point</h2><p className="mt-4 leading-7 text-slate-700">Mahjong developed in China in the nineteenth century before spreading internationally and taking on local forms. American Mahjong is one of those adaptations, not a replacement for Chinese traditions or other regional versions. Learn the origin of the game alongside the version you are playing, and avoid treating the tiles as merely an aesthetic trend. Stanford historian Annelise Heinz has written about Mahjong’s long role in Chinese American and Jewish American community life. <a className="font-bold text-teal-800 underline" href="https://history.stanford.edu/news/china-us-game-mahjong-shaped-modern-america-says-stanford-scholar" target="_blank" rel="noopener noreferrer">Read Stanford’s overview</a>.</p></div></section>
  <section className="mb-10 rounded-[2rem] bg-slate-900 p-7 text-white"><h2 className="text-3xl font-black">How a typical American Mahjong game works</h2><div className="mt-5 space-y-5 leading-8 text-slate-200"><p>American Mahjong is usually played by four players using racks, dice, tiles, and a current card that lists the legal winning hands for that year. Before ordinary drawing begins, players complete the Charleston: a structured tile-passing sequence that lets everyone improve an initial hand. From there, each player draws a tile, decides whether it helps a plausible hand on the card, and discards one tile. The round ends when a player completes a legal hand and declares Mah Jongg.</p><p>New players do not need to memorize every hand before their first lesson. They do need to understand that American Mahjong is card-driven. The current card is not a casual reference sheet; it determines the valid hand patterns that players pursue. Jokers are also part of the American variation, but they have restrictions—for example, they cannot stand in for a single tile or a pair. The <a className="font-bold text-amber-200 underline" href="https://www.americanmahjonggassociation.com/glossary" target="_blank" rel="noopener noreferrer">American Mahjongg Association glossary</a> is a useful place to learn terms such as Charleston, exposure, joker exchange, and dead hand before a first game.</p><p>Chinese and Japanese Riichi Mahjong operate differently. They do not use the American annual card in the same way, and their scoring and hand requirements should be learned from materials specific to those versions. If a friend says “we play Mahjong,” ask which version, whether you need to bring a current card, and whether the group supplies tiles. That two-minute question prevents most beginner equipment mistakes.</p></div></section>
  <section className="mb-10 rounded-[2rem] border border-amber-100 bg-amber-50 p-7"><h2 className="text-3xl font-black text-slate-900">What a beginner needs—and what can wait</h2><div className="mt-5 space-y-5 leading-8 text-slate-700"><p>For American Mahjong, start by joining a lesson or group before buying an ornate set. If you are forming your own group, buy a readable, complete set with four player racks and pushers, plus the dice and storage needed to keep the pieces together. You may also need a current card, depending on the rules your group follows. A mat, premium acrylic rack, magnetic pusher, score chips, and a specialty case can all improve a regular game night, but none of them matter if the group is using a different rule system from the one your set supports.</p><p>Commercial listings sometimes bundle extra or blank tiles, so do not select a product on the number printed in a title alone. Confirm the tile markings, player equipment, and the version your teacher or group expects. Our first guide, <Link href="/mahjong/best-mahjong-sets-for-beginners" className="font-bold text-teal-800 underline">Best Mahjong Sets for Beginners</Link>, sorts the practical Amazon options for a new American Mahjong table. The next guides in this section will cover travel sets, game-night accessories, version-specific shopping, and a beginner book recommendation.</p></div></section>
  <section className="grid gap-5 md:grid-cols-2">{guides.map((guide, index) => 'href' in guide ? <Link key={guide.title} href={guide.href} className="rounded-[2rem] border border-teal-100 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p className="text-sm font-bold uppercase tracking-wide text-teal-700">#{index + 1} · {guide.status}</p><h2 className="mt-2 text-2xl font-black text-slate-900">{guide.title}</h2><p className="mt-3 leading-7 text-slate-700">{guide.text}</p></Link> : <div key={guide.title} className="rounded-[2rem] border border-slate-200 bg-slate-50 p-6"><p className="text-sm font-bold uppercase tracking-wide text-slate-500">#{index + 1} · {guide.status}</p><h2 className="mt-2 text-2xl font-black text-slate-800">{guide.title}</h2><p className="mt-3 leading-7 text-slate-600">{guide.text}</p></div>)}</section>
</main> }
